volumes:
  sqlserver_data:
networks:
    homestation:
        driver: bridge

services:
    homestation_db:
        container_name: homestationDb
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - SA_PASSWORD=Pass@word
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        networks:
            - homestation
        volumes:
            - sqlserver_data:/var/opt/mssql
        restart: always
        
    homestation_api:
        container_name: homestationApi
        environment:
            - ASPNETCORE_HTTP_PORTS=80
        build:
            context: ./Web
            dockerfile: Dockerfile
        ports:
            - "1883:1883"
            - "9081:80"
        networks:
            - homestation
        depends_on:
            homestation_db:
                condition: service_started
        restart: always
    
    homestation_web:
        container_name: homestationWeb
        build:
            context: ./Web/web.client
            args:
                - TARGET_URL=http://homestationApi/
        ports:
            - "9080:80"
            - "9443:443"
        depends_on:
            - homestation_api
        networks:
            - homestation
        restart: always