volumes:
  sqlserver_data:
networks:
    homestation:
        driver: bridge

services:
    homestation_db:
        container_name: homestationDb
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - SA_PASSWORD=<AwesomePassword>
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        networks:
            - homestation
        volumes:
            - sqlserver_data:/var/opt/mssql
        restart: always
        
    homestation_api:
        container_name: homestationApi
        environment:
            - ASPNETCORE_HTTP_PORTS=80
            - Database__ConnectionString=Data Source=localhost,1433;Database=homestation;User Id=sa;Password=<AwesomePassword>;Encrypt=False;TrustServerCertificate=True
        build:
            context: ./Web
            dockerfile: Dockerfile
        ports:
            - "1883:1883"
            - "8180:80"
        networks:
            - homestation
        depends_on:
            homestation_db:
                condition: service_started
        restart: always
    
    homestation_web:
        container_name: homestationWeb
        build:
            context: ./Web/web.client
            args:
                - HREF=/homestation/ #If you want to use /homestation/ suffix to address otherwise replace with /
        ports:
            - "8080:80"
            - "8443:443"
        depends_on:
            - homestation_api
        networks:
            - homestation
        restart: always