apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.35.0 (9532ceef3)
  name: homestationapi-deployment
  namespace: homestation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homestationapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homestationapi
    spec:
      containers:
        - env:
            - name: MQTT__Port
              value: "1883"
            - name: MQTT__Address
              value: "0.0.0.0"
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: Database__ConnectionString
              value: "" #example, move to secrets
          image: 127.0.0.1:5000/homestation2-homestation_api:latest #specify image registry
          name: homestationapi
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 9180
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: homestationapi
  name: homestationapi
  namespace: homestation
spec:
  ports:
    - name: "1883"
      port: 9883
      protocol: TCP
      targetPort: 1883
    - name: "80"
      port: 9180
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: homestationapi