apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.35.0 (9532ceef3)
  name: homestationapi-deployment
  namespace: homestation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homestationapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homestationapi
    spec:
      containers:
        - env:
            - name: MQTT__Port
              value: "1883" #Pod Internal MQTT Port
            - name: MQTT__Address
              value: "0.0.0.0" #Listen on all
            - name: ASPNETCORE_HTTP_PORTS
              value: "80" #Pod internal HTTP port
            - name: Database__ConnectionString
              valueFrom:
                secretKeyRef:
                  key: ConnectionString
                  name: homestation-secrets
          image: 127.0.0.1:5000/homestation2-homestation_api:latest #specify image registry
          name: homestationapi
          ports:
            - containerPort: 1883 #Customize MQTT port
              protocol: TCP
            - containerPort: 8180 #Customize HTTP port
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: homestationapi
  name: homestationapi
  namespace: homestation
spec:
  ports:
    - name: "1883" #Customize MQTT port
      port: 1883 #Service port to communication, should be the same in a ingress
      protocol: TCP
      targetPort: 1883 #Container port should be the same as target port
    - name: "80" #Customize HTTP port, rules same as above
      port: 9180
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: homestationapi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homestationapiingress
  namespace: homestation
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  rules:
    - http:
        paths:
          - path: /api/(.*)
            backend:
              service:
                name: homestationapi
                port:
                  number: 9180 #HTTP port
            pathType: ImplementationSpecific
  ingressClassName: nginx