apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homestation
  annotations:
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.35.0 (9532ceef3)
  name: homestationweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homestationweb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.yaml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        app.kubernetes.io/name: homestationweb
    spec:
      containers:
        - image: 127.0.0.1:5000/homestation2-homestation_web:latest #specify registry
          name: homestationweb
          env:
            - name: TARGET_URL
              value: "http://homestationApi/homestation/"
          ports:
            - name: "https"
              containerPort: 8443 #Customize HTTPS port - will be deleted in future, ingress configuration uses HTTP
            - name: "http"
              containerPort: 8080 #Customzize HTTP port
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: homestation
  annotations:
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: homestationweb
  name: homestationweb
spec:
  ports:
    - name: "http" #customize HTTP port
      port: 8080 #Service port to communication, should be the same in a ingress
      protocol: TCP
      targetPort: 80
    - name: "https" #customize HTTPS port
      port: 8443 #Service port to communication, should be the same in a ingress
      protocol: TCP
      targetPort: 443 
  selector:
    app.kubernetes.io/name: homestationweb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homestationwebingress
  namespace: homestation
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /homestation/
spec:
  rules:
    - http:
        paths:
          - path: /homestation/
            backend:
              service:
                name: homestationweb
                port:
                  number: 8080 #Exposed HTTP port, should be the same as service port
            pathType: Prefix
  ingressClassName: nginx