apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.35.0 (9532ceef3)
  name: homestationweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homestationweb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.yaml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        app.kubernetes.io/name: homestationweb
    spec:
      containers:
        - image: 127.0.0.1:5000/homestation2-homestation_web:latest #specify registry
          name: homestationweb
          ports:
            - name: "https"
              containerPort: 9443
            - name: "http"
              containerPort: 9080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: homestationweb
  name: homestationweb
spec:
  ports:
    - name: "http"
      port: 9080
      protocol: TCP
      targetPort: 80
      #nodePort: 30080
    - name: "https"
      port: 9443
      protocol: TCP
      targetPort: 443
      #nodePort: 30443
  selector:
    app.kubernetes.io/name: homestationweb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homestationwebingress
  namespace: homestation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /homestation/$2
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /homestation(/|$)(.*)
            backend:
              service:
                name: homestationweb
                port:
                  number: 80
            pathType: Prefix